// <auto-generated />
using System;
using BookDB.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookDB.Api.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20190122084659_Customers_Groups_Seed_Data")]
    partial class Customers_Groups_Seed_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("BookDB.Api.Entites.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ISBN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "9789140674029",
                            Author = "Magnus Lilja, Ulrik Nilsson",
                            ImageUrl = "https://s2.adlibris.com/images/1796891/programmering-1-c.jpg",
                            Title = "Programmering 1 C#"
                        },
                        new
                        {
                            ISBN = "9789140677099",
                            Author = "Magnus Lilja, Ulrik Nilsson, Bo Silborn",
                            ImageUrl = "https://s2.adlibris.com/images/2773237/programmering-1-c.jpg",
                            Title = "Programmering 1 C++"
                        },
                        new
                        {
                            ISBN = "9789140677105",
                            Author = "Magnus Lilja, Ulrik Nilsson, Bo Silborn",
                            ImageUrl = "https://s1.adlibris.com/images/966044/programmering-1-java.jpg",
                            Title = "Programmering 1 Java"
                        });
                });

            modelBuilder.Entity("BookDB.Api.Entites.BookCopy", b =>
                {
                    b.Property<string>("BookId");

                    b.Property<int>("CopyNumber");

                    b.Property<string>("Description");

                    b.HasKey("BookId", "CopyNumber");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            BookId = "9789140674029",
                            CopyNumber = 1
                        },
                        new
                        {
                            BookId = "9789140674029",
                            CopyNumber = 2
                        },
                        new
                        {
                            BookId = "9789140674029",
                            CopyNumber = 3
                        },
                        new
                        {
                            BookId = "9789140674029",
                            CopyNumber = 4
                        },
                        new
                        {
                            BookId = "9789140674029",
                            CopyNumber = 5
                        },
                        new
                        {
                            BookId = "9789140677099",
                            CopyNumber = 1
                        },
                        new
                        {
                            BookId = "9789140677099",
                            CopyNumber = 2
                        },
                        new
                        {
                            BookId = "9789140677099",
                            CopyNumber = 3
                        },
                        new
                        {
                            BookId = "9789140677099",
                            CopyNumber = 4
                        },
                        new
                        {
                            BookId = "9789140677099",
                            CopyNumber = 5
                        },
                        new
                        {
                            BookId = "9789140677105",
                            CopyNumber = 1
                        },
                        new
                        {
                            BookId = "9789140677105",
                            CopyNumber = 2
                        },
                        new
                        {
                            BookId = "9789140677105",
                            CopyNumber = 3
                        },
                        new
                        {
                            BookId = "9789140677105",
                            CopyNumber = 4
                        },
                        new
                        {
                            BookId = "9789140677105",
                            CopyNumber = 5
                        });
                });

            modelBuilder.Entity("BookDB.Api.Entites.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<Guid>("GroupId");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.HasKey("CustomerId");

                    b.HasIndex("GroupId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("f9e9f3f1-9a31-4af9-84c9-9b60154f7887"),
                            Firstname = "Leona",
                            GroupId = new Guid("ac9c8a4d-656c-44eb-9a96-62faa5ce050e"),
                            Lastname = "Perry"
                        },
                        new
                        {
                            CustomerId = new Guid("4ea68fd8-c632-41e0-95ad-445559e551f6"),
                            Firstname = "Khalil",
                            GroupId = new Guid("ac9c8a4d-656c-44eb-9a96-62faa5ce050e"),
                            Lastname = "Trelawney"
                        },
                        new
                        {
                            CustomerId = new Guid("0c5a5aa0-ee03-482a-a5cd-81e18856dd19"),
                            Firstname = "Marcia",
                            GroupId = new Guid("f87f4b0d-345c-4240-aa12-7126b5e6a7b5"),
                            Lastname = "O'Doherty"
                        },
                        new
                        {
                            CustomerId = new Guid("a2bf8bfc-8cd4-44fe-80fd-51a3531aadaa"),
                            Firstname = "Mathilde",
                            GroupId = new Guid("f87f4b0d-345c-4240-aa12-7126b5e6a7b5"),
                            Lastname = "Mills"
                        },
                        new
                        {
                            CustomerId = new Guid("09c29016-7d6d-4bc0-b55f-13da76f418c3"),
                            Firstname = "Aniela",
                            GroupId = new Guid("f87f4b0d-345c-4240-aa12-7126b5e6a7b5"),
                            Lastname = "Freeman"
                        });
                });

            modelBuilder.Entity("BookDB.Api.Entites.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = new Guid("ac9c8a4d-656c-44eb-9a96-62faa5ce050e"),
                            GroupName = "TE18:1"
                        },
                        new
                        {
                            GroupId = new Guid("f87f4b0d-345c-4240-aa12-7126b5e6a7b5"),
                            GroupName = "TE18:2"
                        },
                        new
                        {
                            GroupId = new Guid("6aad4c8c-e11c-4d90-b789-dd225fcbf452"),
                            GroupName = "ES18:1"
                        },
                        new
                        {
                            GroupId = new Guid("8bafeac9-7c73-4448-bc12-59ed95d02186"),
                            GroupName = "ES18:2 "
                        },
                        new
                        {
                            GroupId = new Guid("d5e77fbe-0dc1-4968-ab12-cdd41d42a7b9"),
                            GroupName = "EE18A"
                        });
                });

            modelBuilder.Entity("BookDB.Api.Entites.BookCopy", b =>
                {
                    b.HasOne("BookDB.Api.Entites.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookDB.Api.Entites.Customer", b =>
                {
                    b.HasOne("BookDB.Api.Entites.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
